    $(function(){
        $("#includedContentHeader").load("includes/header.html"); 
    });
    $(function(){
        $("#includedContentFooter").load("includes/footer.html"); 
    });
    $(function(){
        $("#includedContentSpelregels").load("includes/spelregels.html"); 
    });
    $(function(){
        $("#includedContentUitrusting").load("includes/uitrusting.html"); 
    });
    $(function(){
        $("#includedContentMenu").load("includes/menu.html"); 
    });

$(document).ready(function(){
    $("p").click(function(){
        $(this).hide();
    });
    $("p").click(function(){
        $("#mmt").val('TEST');
    });
});
